theme: jekyll-theme-minimal
title: HyperBMC
description: BMC-Centric, Software-Defined Platform Management for Datacenter Efficiency, Security, and Low Entropy
logo: https://avatars.githubusercontent.com/u/55422153?v=4